var i18n = {
  current_language: 'en',
  js_wrong_password_please_try_again: 'Wrong password - please try again',
  js_help: 'Help',
  js_you_are_working_offline_now_can_edit_and_create_new_maps: 'You are working offline now. You can edit all available maps as well as create new maps.',
  js_signout: 'Sign out',
  js_certain_features_may_not_be_available: 'Certain features may not be available',
  js_upgrade: 'Upgrade',
  js_please_wait_for_map_synchronization: 'Please wait for map synchronization',
  js_please_wait_for_attachments_synchronization: 'Please wait for attachments upload',
  js_taking_s_maps_offline_s: 'Taking %s maps ',
  js_no_permissions_to_perform_this_action: 'You don\'t have permissions to perform this action.',
  js_conflict_detected_on: 'Conflict detected on ',
  js_clone: 'Clone',
  js_map_modified_online_please_choose_action: ' The map was modified on the server while you were offline. Please choose one of the options below.',
  js_email_invalid: 'Please enter a valid email address',
  js_discard_changes: 'Discard changes',
  js_text_outline: 'Text Outline',
  js_save_as_new_map: 'Save as new map',
  js_undelete: 'Undelete',
  js_print: 'Print',
  js_map_info: 'Map Info',
  js_theme: 'Theme',
  js_error_commiting_offline_changes: 'Error committing offline changes',
  js_keepaligned: 'Keep aligned',
  js_cant_go_online_we_are_sorry_force_online: 'There was a problem committing your changes. We\'re very sorry and are trying to fix the issue as soon as possible. Do you want to force going online now?',
  js_report_abuse: 'Report Abuse',
  js_you_will_loose_all_press_no_end_export_first: 'You will lose all your offline changes. We recommend to copy the changes code below and send it to support@mindmeister.com to restore unsaved changes.',
  js_search: 'Search',
  js_yes: 'Yes',
  js_october: 'October',
  js_no: 'No',
  js_filter_author: 'Editing user',
  js_connection_to_server_lost: 'Connection to server lost!',
  js_trashcan_warning: 'Are you sure you want to empty your trashcan? This operation cannot be undone and your maps will be deleted forever.',
  js_none_is_editing_on_this_map_now: 'No one else is editing this mind map',
  js_emptying_trashcan: 'Emptying trashcan...',
  js_cant_delete_root_note: 'Cannot delete root node!',
  js_notice: 'Notice',
  js_must_select_something_first: 'You have to select something first.',
  js_october_short: 'Oct',
  js_cant_move_root_note: 'You cannot move the root node.',
  js_invalid_image: 'Invalid image',
  js_must_select_destination: 'You have to select the destination.',
  js_numbering: 'Number',
  js_must_cut_something_first: 'You have to cut something first.',
  js_connection_delete: 'Delete Connection',
  js_cant_paste_in_same_tree: 'Cannot paste in same tree.',
  js_connection_color: 'Connection Color',
  js_ambiguos_action: 'Ambiguous action.',
  js_you_cant_do_things_become_premium_to_do_that_s: '<em>Sorry, %s is for paid accounts only</em>Upgrade your account to %s.',
  js_please_select_an_idea_first: 'Please select an idea first',
  js_myteam: 'My Team',
  js_attachments: 'Attachments',
  js_are_you_sure: 'Are you sure?',
  js_task_information: 'Task Information',
  js_offline: 'Offline',
  js_due_date: 'Due Date:',
  js_online: 'Online',
  js_start_date: 'Start Date:',
  js_settings: 'Settings...',
  js_duration: 'Duration',
  js_make_admin: 'Make admin',
  js_assigned_to: 'Assigned To:',
  js_make_normal_member: 'Remove from admins',
  js_external_link: 'External link',
  js_disable_account: 'Disable',
  js_about_thumbshot_thumbails: 'About Thumbshots thumbnails',
  js_enable_account: 'Enable',
  js_email_link: 'Email link',
  js_link_to_topic: 'Link to topic',
  js_in_this_map: 'in this map',
  js_maximum_zoomlevel_reached: 'Maximum zoom level reached.',
  js_please_note_browser_not_supported_link: 'Please note that your browser isn\'t supported by MindMeister. See a %slist of supported browsers%s.',
  js_minimum_zoomlevel_reached: 'Minimum zoom level reached.',
  js_year: 'year',
  js_google_could_not_be_contacted: 'Google could not be contacted. Please try again later.',
  js_check_out_this_map: 'Check out this MindMeister mind map:',
  js_month: 'month',
  js_ok: 'OK',
  js_copy_link: 'Copy Link',
  js_topic: 'Topic',
  js_saving: 'Saving...',
  js_info: 'Info',
  js_warning: 'Warning',
  js_error: 'Error',
  js_did_you_know: 'Did you know?',
  js_january_short: 'Jan',
  js_february_short: 'Feb',
  js_march_short: 'Mar',
  js_april_short: 'Apr',
  js_june_short: 'Jun',
  js_july_short: 'Jul',
  js_august_short: 'Aug',
  js_september_short: 'Sep',
  js_november_short: 'Nov',
  js_december_short: 'Dec',
  js_sunday: 'Sunday',
  js_monday: 'Monday',
  js_tuesday: 'Tuesday',
  js_wednesday: 'Wednesday',
  js_thursday: 'Thursday',
  js_friday: 'Friday',
  js_saturday: 'Saturday',
  js_sunday_short: 'Sun',
  js_monday_short: 'Mon',
  js_tuesday_short: 'Tue',
  js_wednesday_short: 'Wed',
  js_thursday_short: 'Thu',
  js_close: 'Close',
  js_friday_short: 'Fri',
  js_learn_more: 'Learn more',
  js_saturday_short: 'Sat',
  js_please_select_something_first: 'Please select an item in the list first by clicking on the respective row',
  js_public_map: 'PUBLIC',
  js_delete_folder: 'Delete Folder',
  js_view_only_map: 'VIEW ONLY',
  js_delete_folder_warning: 'All this folder\'s contents will be removed.',
  js_network_error: 'Network error',
  js_priority: 'Priority',
  js_new_folder: 'New Folder',
  js_retrying_in_seconds: 'retrying in 10 seconds.',
  js_node_copied_unavailable: 'The node you copied is not available anymore',
  js_edit_folder: 'Edit Folder',
  js_confirm_leave_page: 'Some changes have not been saved on the server.',
  js_node_cut_unavailable: 'The node you cut is not available anymore',
  js_name: 'Name',
  js_details: 'Details',
  js_you_cant_do_that_now: 'Sorry, you can\'t do that now.',
  js_unsupported_file_type: 'Unsupported file type',
  js_the_following_attachments_failed: 'The following attachments could not be taken online:',
  js_an_error_occured: 'An error occurred',
  js_no_internet_connection_available_now: 'This action requires internet connection and no internet connection is available to you at the moment',
  js_invalid_attachment: 'Invalid attachment',
  js_invalid_attachment_will_be_removed: 'This attachment is invalid (exceeds size), it was removed from your node. Please try again with another file.',
  js_invalid_task_date: 'Invalid due date for task. Please set a valid date for this task',
  js_map_saved: 'Map saved...',
  js_invalid_link: 'Invalid link: ',
  js_there_are_no_revisions_for_this_map_it_was_not_modified_yet: 'There are no revisions for this mind map. Most likely it was not modified yet.',
  js_external_save_successful: 'Changes to your map saved successfully!',
  js_external_save_failed: 'Failed to save changes to your map',
  js_group_chat: 'Group chat',
  js_your_request_was_not_done: 'Request failed',
  js_older_messages: 'Show earlier messages',
  js_we_are_sorry_request_was_not_done: 'We\'re sorry, but your request was not completed this time. An error occurred. Please try again.',
  js_errors_occured_while_getting_changes: 'Errors occured while getting the changes from the server.',
  js_helper_hours: 'hours',
  js_cancel_invitations_warning: 'Invitations will not be sent - please confirm.',
  js_history_inserted: ' inserted <em class="change">%s</em>',
  js_history_renamed: ' renamed <em class="change">%s</em> to <em class="change">%s</em>',
  js_filter_all: 'All',
  js_history_removed: ' removed <em class="change">%s</em>',
  js_history_repositioned: ' repositioned <em class="change">%s</em>',
  js_filter_idea: 'Idea caption',
  js_history_moved: ' moved <em class="change">%s</em>',
  js_filter_task: 'Task owner',
  js_history_removed_icon_from: ' removed an icon from <em class="change">%s</em>',
  js_history_added_icon_to: ' added an icon to <em class="change">%s</em>',
  js_history_added_text_style_to: ' added a text style to <em class="change">%s</em>',
  js_edit_map_theme: 'Customize map theme...',
  js_history_added_note_to: ' added a note to <em class="change">%s</em>',
  js_clear_color: 'Clear Color',
  js_history_removed_note_from: ' removed the note from <em class="change">%s</em>',
  js_history_added_link_to: ' added a link to <em class="change">%s</em>',
  js_history_removed_task_from: ' removed the task from <em class="change">%s</em>',
  js_history_added_task_to: ' added a task to <em class="change">%s</em>',
  js_history_added_attachment_to: ' added an attachment to <em class="change">%s</em>',
  js_duplicating: 'Duplicating...',
  js_history_removed_attachment_from: ' removed an attachment from <em class="change">%s</em>',
  js_history_added_connection: ' added a connection from <em class="change">%s</em> to <em class="change">%s</em>',
  js_history_removed_connection: ' removed the connection from <em class="change">%s</em> to <em class="change">%s</em>',
  js_history_edited_map_theme: ' changed the map theme',
  js_history_created_the_map: ' created the map',
  js_you_still_have_tasks_sure_want_to_withdraw: 'You still have tasks assigned in this mind map. Are you sure you want to withdraw?',
  js_s_still_has_tasks_sure_want_to_remove_s: '%s still has tasks assigned in this mind map. Are you sure you want to remove %s from the sharing list?',
  js_removing_collaborator: 'Removing collaborator',
  js_publish: 'Publish',
  js_inaccessible_map: 'Inaccessible Map',
  js_map_not_share_with_u_anymore_contact_s: 'This map is not shared with you anymore. Please contact the owner %s and ask them to share it with you again.',
  js_please_wait_while_we_save_to_google_docs: 'Please wait while we save your map to Google Docs....',
  js_you_are_about_to_withdraw: 'You are about to withdraw from',
  js_history_added_image_to_s: ' added an image to <em class="change">%s</em>',
  js_history_removed_image_from_s: ' removed the image from <em class="change">%s</em>',
  js_history_resized_image_on_s: ' resized image on <em class="change">%s</em>',
  js_invite_people: 'Invite People',
  js_node_has_no_image: 'Selected node has no image',
  js_image_could_not_be_found: 'Image could not be found',
  js_upload_new_image: 'Upload a new image...',
  js_use_an_image_from_the_web: 'Use web image...',
  js_browse_image_library: 'Browse image library...',
  js_mindmeister_default: 'Mindmeister Default',
  js_please_wait_for_caching_files: 'Updating offline cache',
  js_overdue: 'Overdue',
  js_no_default_images: 'No default images',
  js_override_theme: 'Custom styles found',
  js_no_image_selected: 'You have to select an image first',
  js_override_theme_text: 'Some node styles in this map have been modified from the theme defaults. Do you want to keep these custom styles or override with the new theme?',
  js_browser_not_supported: 'Browser not supported',
  js_no_image_was_found: 'No images found - please try and shorten your search terms',
  js_keep: 'Keep',
  js_no_auto_image_was_found: 'No WunderBild found for topic',
  js_override: 'Override',
  js_browse_icon_library: 'Browse icon library...',
  js_note_is_too_long: 'The note is too long',
  js_you_can_undo_afterwards: 'You can undo all changes afterwards.',
  js_offline_mode: 'Offline Mode',
  js_scrollbars: 'Scrollbars',
  js_images_s: '%s images',
  js_use_new_browser_for_offline_mode: 'The MindMeister Offline Mode uses advanced HTML5 features which are currently available only in Google Chrome and Safari. Firefox and Internet Explorer will be supported as soon as HTML5 support becomes sufficient.',
  js_icons_s: '%s icons',
  js_error_caching_files: 'Error caching files',
  js_history_edited_note_on: ' edited the note on <em class="change">%s</em>',
  js_cant_cache_every_file: 'There was a problem caching the files for the offline mode. We\'re very sorry and are trying to fix the issue as soon as possible. Do you want to go online now?',
  js_history_edited_task_on: ' edited the task on <em class="change">%s</em>',
  js_history_removed_link_from: ' removed link from <em class="change">%s</em>',
  js_history_edited_link_on: ' edited the link on <em class="change">%s</em>',
  js_no_guarantee_of_losing_changes_retry_first: 'We could not guarantee that no offline changes are lost (so you might want to press No and retry to cache the files for the offline mode)',
  js_priority_s: 'Priority %s',
  js_offline_feature_unavailable_on_this_browser: 'Your Browser does not support this feature yet.',
  js_cancel: 'Cancel',
  js_delete_items: 'Delete items',
  js_there_are_no_suggestions: 'There are no suggestions. Please try another search term.',
  js_new_node: 'New node',
  js_one_child_idea: 'One child idea',
  js_delete_folders_warning: 'All the folders\' contents will be removed',
  js_more_child_ideas_d: '%d child ideas',
  js_direct_link: 'Direct link',
  js_show_detail: 'Show Detail',
  js_apply_to_branch: 'Apply to Branch',
  js_no_border_set: 'Selected node has no border. Please choose a theme containing borders before.',
  js_tools: 'Tools',
  js_one_level: 'One Level',
  js_two_levels: 'Two Levels',
  js_all: 'All',
  js_color: 'Color',
  js_font_size: 'Font Size',
  js_font_style: 'Font Style',
  js_alphabetize: 'Alphabetize',
  js_modified_by_s_s: 'Modified by %s on %s',
  js_image_unavailable: 'Image unavailable',
  js_cloned_revision: 'The current revision has been saved as a new mind map in your maps list.',
  js_revert_to_revision_warning: 'All changes since revision %s will be irreversibly lost. Are you sure you want to continue?',
  js_no_images: 'No images',
  js_clone_public_map: 'Clone public map',
  js_images_d: '%d images',
  js_do_you_want_to_clone_map_to_account: 'Do you want to copy this mind map to your account?',
  js_google_cannot_be_contacted: 'You are now working offline. Google cannot be contacted.',
  js_image_not_available: 'Image not available',
  js_iconfinder_could_not_be_contacted: 'Icon Finder could not be contacted. Please try again later.',
  js_history_changed_an_icon_s: ' changed an icon on <em class="change">%s</em>',
  js_history_set_the_priority_of_a_task_to_s_s: ' set the priority of <em class="change">%s</em> to %s',
  js_create_as_map: 'Create as Map',
  js_create_as_map_explanation: 'This will create a new map from the selected idea and all child ideas will be moved to the new map.',
  js_connect_node_to_itself: 'Cannot connect a node to itself.',
  js_create_as_map_add_link: 'Add link to new map',
  js_links: 'Links',
  js_create_as_map_preserve_permissions: 'Preserve sharing permissions',
  js_tasks: 'Tasks',
  js_c_to_copy_content_to_clipboard: '-C to copy contents to your clipboard',
  js_notes: 'Notes',
  js_remove_icon: 'Remove Icon',
  js_history_set_a_task_to_completed_d_s: ' set the task <em class="change">%s</em> to %s completed',
  js_cut: 'Cut',
  js_click_to_filter_by_this_user: 'Click to filter changes by this user',
  js_copy: 'Copy',
  js_click_to_filter_by_this_idea: 'Click to filter changes by this idea',
  js_paste: 'Paste',
  js_view_changes_on_this_idea: 'View Changes...',
  js_copy_as_text: 'Copy as Text',
  js_edit: 'Edit',
  js_edit_caption: 'Edit Caption',
  js_history_changed_connection_color: ' changed connection color from <em class="change">%s</em> to <em class="change">%s</em>',
  js_note: 'Note',
  js_no_matches_found: 'No matches found',
  js_add_note: 'Add Note',
  js_edit_note: 'Edit Note',
  js_this_image_may_be_subject_to_copyright: 'This image may be subject to copyright',
  js_open_source_page: 'View on source page',
  js_no_icon_selected: 'You have to select an icon first',
  js_image_does_not_match: 'Image does not match',
  js_no_auto_note_found_for_topic: 'No WunderNote found for topic',
  js_loading_image: 'Loading image',
  js_getting_auto_link: 'getting WunderLink',
  js_start_date_is_set_after_due_date: 'Start date is set after due date',
  js_no_link_found_for_topic: 'No WunderLink found for topic',
  js_offline_word: 'offline',
  js_no_attachments: 'No attachments',
  js_me: 'Me',
  js_remove_attachment: 'Remove attachment',
  js_remove: 'Remove',
  js_open: 'Open',
  js_duplicate: 'Duplicate',
  js_you_cannot_use_undo_redo_in_collaborative_mode: 'Please exit brainstorming mode by asking collaborators to close the map in order to undo changes safely.',
  js_delete: 'Delete',
  js_share: 'Share',
  js_you_are_about_to_delete_items_s: 'You are about to delete the following items: %s',
  js_items_s: '(%s items)',
  js_export: 'Export',
  js_properties: 'Properties',
  js_delete_mind_map: 'Delete Mind Map',
  js_you_are_about_to_delete: 'You are about to delete',
  js_do_you_want_to_continue: 'Do you want to continue?',
  js_january: 'January',
  js_february: 'February',
  js_march: 'March',
  js_april: 'April',
  js_helper_days: 'days',
  js_may: 'May',
  js_helper_weeks: 'weeks',
  js_june: 'June',
  js_helper_months: 'months',
  js_july: 'July',
  js_no_results_received: 'No results found',
  js_august: 'August',
  js_september: 'September',
  js_november: 'November',
  js_december: 'December',
  js_critical_error_occured: 'A critical error has occured in MindMeister.',
  js_event_logged_and_error_will_be_corected: 'We\'re sorry for the inconvenience, the event has been logged and the error will be corrected as soon as possible.',
  js_this_map_cant_be_initialized: 'This map cannot be initialized',
  js_press_ok_to_reload_page: 'Please press OK to reload the page.',
  js_status_updating_changes_from_server: 'Status: updating changes from server',
  js_status_idle: 'Status: idle',
  js_entering_brainstorming_mode: 'Entering brainstorming mode',
  js_you_are_in_view_only_mode: 'You are in view only mode',
  js_other_users_editing: ' - other users are currently editing',
  js_copied_to_clipboard: 'Copied to clipboard',
  js_none: 'None',
  js_not_started: 'Not started',
  js_complete: 'Complete',
  js_done_lower: 'done',
  js_edit_label: 'Edit label',
  js_cant_copy_into_self_or_children: 'Cannot copy into self or children!',
  js_error_encountered_when_taking_maps_offline: 'Error encountered when taking maps offline!',
  js_myaccount: 'My Account',
  js_you_are_not_connected_to_internet_connect_and_try_again: 'You are not connected to the internet. Please connect and try again.',
  js_admin: 'Admin',
  js_error_encountered_when_putting_maps_online: 'Error encountered when putting maps back online.',
  js_translate: 'Translate'
}